services:
  db:
    image: postgres:16.1
    container_name: db
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    healthcheck:
      # checking when the database is ready for the flask app to wait
      test: ["CMD-SHELL", "pg_isready -U ${RDS_USERNAME} -d ${RDS_DB_NAME}"]
      interval: 5s
      timeout: 20s
      retries: 5

  flask:
    build: ./flask
    container_name: flask
    env_file:
      - .env
    depends_on:
      db:
        # waiting for the database to be ready
        condition: service_healthy

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl-certs:/etc/nginx/ssl-certs
  #   depends_on:
  #     - flask
