services:
  db-test:
    image: postgres:15.2
    container_name: db-test
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db-v:/var/lib/postgresql/datatmp
    healthcheck:
      # checking when the database is ready for the flask app to wait
      test: ["CMD-SHELL", "pg_isready -U psql -d db"]
      interval: 5s
      timeout: 20s
      retries: 5

  flask-test:
    build: ./flask
    container_name: flask-test
    ports:
      - "5000:5000"
    depends_on:
      db-test:
        # waiting for the database to be ready
        condition: service_healthy
    volumes:
      - ./flask:/app

# to persist container volumes
volumes:
  db-v:
